### ISSUE TITLE
Renaming of finos-fo repo to financial-objects

### ISSUE THREAD

**Issue by mcleo-d** [finos/financial-objects#32]
## Description

The name of the Financial Objects repository on GitHub `finos-fo` does not describe the project and is potentially difficult to find in the FINOS organisation and through GitHub and Google Search. 

## Potential Solution

By renaming the FINOS Financial Objects repository from `finos-fo` to `financial-objects` the new repo name describes the project and becomes easier to find in the FINOS GitHub organisation and through search.    

The reference to FINOS is also maintained through the FINOS organisation on GitHub which is referred to within the following URL - `https://github.com/finos/financial-objects` 

## Potential Risks

1. The current url `https://github.com/finos/finos-fo/` is indexed on Google and is driving traffic to the project.
2. The current url `https://github.com/finos/finos-fo/` is referred to in documentation and will potentially need to change.
3. The current url `https://github.com/finos/finos-fo/` is referred to in code and will potentially need to change.

## Next Steps

The viability of the change should be assessed by the Financial Objects project and potentially be discussed on an Open Developer Platform project call before prioritising the change if relevant.

**Comment by maoo** [comment]
@grizzwolf - any word of wisdom re. the risks around Google indexing? I suppose it's possible to use Google online tools to ask a reindexing of those pages - and remove old references, right?

@mcleo-d - In any case, GitHub will provide a redirect, so we won't loose traffic.

**Comment by finos-admin** [comment]
done!
