### ISSUE TITLE
CDM Event Modelling - KnockIn Function

### ISSUE THREAD

**Issue by Vijayesh-Chandel** [finos/financial-objects#66]
## CDM Event Modelling - KnockIn Function

As part of Phase 2 of the FX Pilot for Legend Studio, the WG had designed a CDM event function for KnockIn (KI) lifecycle events: 
[See Minutes 9Jul20 for details](https://github.com/finos/legend/issues/179). 

At the time the Studio feature for creating functions was to be built and submission was pending, but now the feature is ready for use.

The following CDM primitives formed the proposed KI function:
- ObservationPrimitive
- ExercisePrimitive 

However the CDM event model has since evolved and these primitives are deprecated. As a result, the proposed KI function will need further review and update, and ask is to collaborate on creating a new KI function solution for the CDM.

**Comment by JamesR5270** [comment]
Hello, happy to get involved - I work for Skylight IPV covering FX options.  James

**Comment by Vijayesh-Chandel** [comment]
> Hello, happy to get involved - I work for Skylight IPV covering FX options. James

Hi  @JamesR5270, thanks for reaching out, be great to have you onboard. We're working on formalising a working group for this, will keep you posted.
Best,
Vijay

**Comment by rvincentISDA** [comment]
Hi, Include me in the thread. Thank you

**Comment by Vijayesh-Chandel** [comment]
Hi all - we'll be starting a WG for this topic on 22nd September 2021 as part of the FO SIG. Details/calendar invites will be shared soon.
Thanks,
Vijay

**Comment by markajeffries** [comment]
Hi Vijay, 
I have recently joined Skylight IPV and have taken over from James to head up our FX options service. Can you please include me on this going forwards?
Thanks,
Mark

**Comment by Vijayesh-Chandel** [comment]
Hi @markajeffries - yes sure will include yourself. We are currently working through the planning of the WG with FINOS who will share more details soon. 
Thanks,
Vijay

**Comment by ffionwiggins** [comment]
This will be the first issue tackled in the Structured Products Working Group. Look out for the upcoming invitations.
